# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 22:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, b'Dog'), (2, b'Cat')], default=1, max_length=40, verbose_name=b'Type')),
                ('name', models.CharField(error_messages={b'required': b'Name is required.'}, max_length=50, verbose_name=b'Name')),
                ('birthday', models.DateField(error_messages={b'required': b'Birthday is required.'}, verbose_name=b'Birthday')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
